apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-hello-world
  template:
    metadata:
      labels:
        app: my-hello-world
    spec:
      containers:
      - name: my-hello-world-container
        image: [dockerhub계정]my-hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
